### PR TITLE
Update export.py

### PR DESCRIPTION
**Pull request by sdutill**
Added encoding to exported template configuration to support YAML output.

### CODE REVIEW

**Comment by sdutill** [comment]
I believe this solves the following issue: https://github.com/unioslo/zabbix-cli/issues/174

**Comment by pederhan** [comment]
Was this a problem on other platforms? The auto-detected encoding was always utf-8 for me on MacOS.

I suppose it doesn't hurt to add it for consistency across all platforms.

Thanks for the contribution!

**Comment by sdutill** [comment]
> Was this a problem on other platforms? The auto-detected encoding was always utf-8 for me on MacOS.
> 
> I suppose it doesn't hurt to add it for consistency across all platforms.
> 
> Thanks for the contribution!

pederhan,

I'm on a Win11 machine and would run crash when trying to export certain templates. Happy this was such an easy fix. Great tool you've built!

**Comment by pederhan** [comment]
Thank you, glad it works for you!

**Pull request merged**
