### PR TITLE
add api functions for showing/updating/deleting host interfaces

### PR DESCRIPTION
**Pull request by FStelzer**
adds hostinterface api functions not existing yet.
there's not really much of a choice other than workin directly with the InterfaceIDs for update/delete calls.

### CODE REVIEW

**Comment by herdir** [comment]
Always return an error
user@computer:~$ zabbix-cli -C "show_host_interfaces 507ro1"

`[ERROR]:'bulk'`

**Comment by mbakke** [comment]
Hi @FStelzer, do you think you will have the opportunity to adjust this for Zabbix 5 or 6?

Thanks, and sorry for the late response :-)

**Comment by FStelzer** [comment]
there seemed to be noch much interest for it and i have switched to using the python api directly long ago.
sorry, but at the moment I have other todos and no real use for this functionality.
Shouldn't be too hard to implement though in case someone needs it.

**Comment by pederhan** [comment]
Added in #186.

**Pull request closed without merging**
